### PR TITLE
Upgrade Needle dependency to fix errors

### PR DESCRIPTION
**Pull request by brianhelba**
Prior to v0.7.9, Needle depended on a floating version of the "qs" library. The latest release of "qs" depends on ECMAScript6, which causes failures when running in any older Node environment.

Upgrading to the latest Needle fixes this issue. There are no compatibility changes between v0.6.1 and v0.11.0 that should cause issues:
https://github.com/tomas/needle/releases

### CODE REVIEW

**Comment by brianhelba** [comment]
@jubalm PTAL. I'd really like to use your library within our project, [Girder](https://github.com/girder/girder), but this issue needs to be fixed first.

Once it's merged, you'll need to also push a new release to NPM.

**Comment by rubensayshi** [comment]
hmm, I can merge but I can't release to NPM :(

**Comment by brianhelba** [comment]
Thanks @rubensayshi . Is it only @jubalm who does the NPM releases? Do you know if he's still active?

If he's not active (the last release to NPM was 2 years ago), I'm going to look into forking the repository, or seeing if the NPM maintainers can add permissions for someone else to release a new package.

This is a very useful tool, so I'd like to make sure it can be practically used in projects.

**Comment by jubalm** [comment]
@brianhelba, apologies for the inactivity will be doing a quick bump with this PR today. You look like you have the most use-case for this repo, feel free to contribute :)

**Comment by simison** [comment]
@jubalm any changes adding @brianhelba and @rubensayshi rights to this repo and NPM? :-) Would be great!

**Comment by jubalm** [comment]
@simison sure, i've already added ruben as collaborator on npm but couldn't seem to figure out @brianhelba 's handle/account there. (Hmm it's really been a while, i thought i could privately message people round github then?)

**Pull request merged**
